version: '3.8'

services:
  bookmark-manager:
    image: ghcr.io/OWNER/REPO:latest  # Update OWNER/REPO with your GitHub username/repository
    networks:
      - bookmark-net
    ports:
      - "5000:5000"
    environment:
      # Bookmark storage configuration
      - BOOKMARKS_PATH=/mnt/nfs/dockerfiles/homepage/bookmarks.yaml
      - ICONS_PATH=/mnt/nfs/dockerfiles/homepage/icons
      
      # Flask configuration
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      
      # Optional: Custom host/port (defaults: 0.0.0.0:5000)
      # - FLASK_HOST=0.0.0.0
      # - FLASK_PORT=5000
    volumes:
      # Persistent storage for bookmarks and icons
      - bookmark-data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bookmark-manager.rule=Host(`bookmarks.yourdomain.com`)"
        - "traefik.http.routers.bookmark-manager.tls=true"
        - "traefik.http.routers.bookmark-manager.tls.certresolver=letsencrypt"
        - "traefik.http.services.bookmark-manager.loadbalancer.server.port=5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bookmark-net:
    driver: overlay
    attachable: true

volumes:
  bookmark-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/bookmark-data